amcl:
  ros__parameters:
    use_sim_time: false  
    max_beams: 60 
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.2
    update_min_a: 0.2
    z_hit: 0.8
    z_short: 0.1
    z_max: 0.05
    z_rand: 0.05
    transform_tolerance: 1.0
    resample_interval: 1
    tf_broadcast: true
    odom_frame_id: "odom"  
    base_frame_id: "base_link"  
    global_frame_id: "map"
    scan_topic: "Scan" 
    use_map_topic: true
    save_pose_rate: 0.5

map_server:
  ros__parameters:
    yaml_filename: "/home/catia/ros2_ws/src/navigation_/config/cappero_laser_odom_diag_2020-05-06-16-26-03.yaml"
    use_sim_time: false
    frame_id: "map"
    resolution: 0.05

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      transform_tolerance: 0.5
      rolling_window: true
      width: 3.0
      height: 3.0
      plugins:
        - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 2.0
      publish_frequency: 2.0
      resolution: 0.05
      transform_tolerance: 0.5
      plugins:
        - {name: static_layer, type: "nav2_costmap_2d::StaticLayer"}
        - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    min_x_velocity: 0.0
    max_x_velocity: 0.26  
    min_theta_velocity: 0.0
    max_theta_velocity: 1.0
    acc_lim_x: 2.5
    acc_lim_theta: 3.2
    decel_lim_x: 2.5
    decel_lim_theta: 3.2

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    max_planning_retries: 5
    max_planning_time: 2.0
    planning_horizon: 10.0
    use_sim_time: false

recoveries_server:
  ros__parameters:
    costmap_topic: "local_costmap/costmap_raw"
    footprint_topic: "local_costmap/published_footprint"
    recovery_behavior_plugin_names: ["spin", "back_up", "wait"]

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
