controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    min_x_velocity: 0.0
    max_x_velocity: 0.26  
    min_theta_velocity: 0.0
    max_theta_velocity: 1.0
    acc_lim_x: 2.5
    acc_lim_theta: 3.2
    decel_lim_x: 2.5
    decel_lim_theta: 3.2
